name: firebae_reg_auth
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.0
  cloud_firestore: ^4.2.0
#  flutter_native_splash: ^2.2.16
  zego_uikit_prebuilt_call: ^1.2.13
  zego_uikit_signaling_plugin: ^1.0.7 # Add this line
  flutter_styled_toast: ^2.1.3
  record: ^4.4.4
  path_provider: ^2.0.14
#  audioplayers: ^3.0.1
  permission_handler: ^10.2.0
#  flutter_svg: ^1.1.5
  google_fonts: ^3.0.1

  syncfusion_flutter_pdf: ^18.4.47-beta
  syncfusion_flutter_signaturepad: ^18.4.47-beta
  http: ^0.13.3
#  audioplayers: ^0.20.1
  open_file: ^3.1.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/helvetica_bold1.ttf
          weight: 700
        - asset: assets/fonts/HelveticaRegular.otf
          weight: 400

    - family: HelveticaCompressed
      fonts:
        - asset: assets/fonts/HelveticaCompressed-Regular.otf
          weight: 400

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
    - audio/
    - assets/page-1/images/